;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname ex0027) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp")) #f)))

;The problem statement specifies how the number of attendees depends on
;the ticket price. Computing this number is clearly a separate task and
;thus deserves its own function definition:

;added by me
(define base-average-attendee 120)
(define base-ticket-cost 5)
(define attendee-variation 15)
(define price-variation 0,1)

    (define (attendees ticket-price)
      (- base-average-attendee (* (- ticket-price base-ticket-cost)
                             (/ attendee-variation price-variation))))

;The revenue is exclusively generated by the sale of tickets, meaning
;it is exactly the product of ticket price and number of attendees:

    (define (revenue ticket-price)
      (* ticket-price (attendees ticket-price)))

;The cost consists of two parts: a fixed part ($180) and a variable
;part that depends on the number of attendees. Given that the number of
;attendees is a function of the ticket price, a function for computing
;the cost of a show must also consume the ticket price so that it can
;reuse the attendees function:

;Addeed by me
(define fixed-cost 180)
(define cost-per-costumer 0.04)

    (define (cost ticket-price)
      (+ fixed-cost (* cost-per-costumer (attendees ticket-price))))

;Finally, profit is the difference between revenue and costs for some
;given ticket price:

    (define (profit ticket-price)
      (- (revenue ticket-price)
         (cost ticket-price)))

;Exercise 27. Our solution to the sample problem contains several
;constants in the middle of functions. As One Program, Many Definitions
;already points out, it is best to give names to such constants so that
;future readers understand where these numbers come from. Collect all
;definitions in DrRacket’s definitions area and change them so that all
;magic numbers are refactored into constant definitions.
